name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: check.sh
      run: sudo chmod +x check.sh && ./check.sh
    - name: make all
      run: make
    - name: make clean
      run: make clean
